apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: harness-demo
  template:
    metadata:
      labels:
        app: harness-demo
    spec:
      containers:
      - image: 1903/harness_demo:11
        name: harness-demo
        ports:
        - containerPort: 80