apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness_demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: harness_demo
  template:
    metadata:
      labels:
        app: harness_demo
    spec:
      containers:
      - image: docker pull 1903/harness_demo:11
        name: harness_demo
        ports:
        - containerPort: 80